<a href="https://colab.research.google.com/github/hydro-7/Krish-Naik-Course/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np


# **Arrays using numpy**


In [3]:
arr1 = np.array([1,2,3,4])
# ^ 1D numpy array
# => [1,2,3,4]
# shape = (, 5) --> (r, c)

arr2 = np.array([1,2,3,4])
arr2.reshape(1,4)
# reshapes it to a 2D numpy array
# [[1,2,3,4]]
# shape = (1, 5)


array([[1, 2, 3, 4]])

Arrange Function

In [8]:
np.arange(0, 10, 2) # 0 2 4 6 8

array([0, 2, 4, 6, 8])

Ones Array

In [9]:
np.ones((3,4)) # 3 r, 4 c all have val = 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.eye(3) # 3 x 3 identity matrix. i.e, all diag elts = 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Vectorized Operations**

Element wise Addition/Subtraction/Multiplication/Division

In [11]:
# Each elt of arr1 is added/sub/mul/div to elt of arr2

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1+arr2) #=> [6,8,10,12]
print(arr1-arr2) #=> [-4,-4,-4,-4]
print(arr1*arr2)
print(arr1/arr2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


Universal Functions

In [12]:
arr = np.array([1,2,3,4])

# Sqrt
print(np.sqrt(arr)) # sqrt(arr[i])

# Exponent
print(np.exp(arr)) # e^arr[i]

# Sine
print(np.sin(arr)) # sin(arr[i])

# Natural log
print(np.log(arr)) # ln(arr[i])

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


# **Array Slicing and Indexing**

In [ ]:
# Instead of arr[i][j] you can use arr[i, j]


# **Stats**

Normalization


In [13]:
data = np.array([1,2,3,4])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean)/std_dev